---
# grog.package
package_list:
  - name: ack
  - name: bat
  - name: curl
  - name: fzf
  - name: git
  - name: htop
  - name: libio-prompter-perl
  - name: libjson-perl
  - name: libjson-xs-perl
  - name: python3-icecream
  - name: python3.10-venv
  - name: python3-pip
  - name: python3-virtualenv
  - name: shellcheck
  - name: shfmt
  - name: sqlite3
  - name: sudo
  - name: tmux
  - name: vim
  - name: wget
  - name: yamllint

apt_cache_proxy: http://10.10.8.140:3142
nvm_version: v0.39.3

# hussainweb.chezmoi
chezmoi_init_url: git@github.com:hannah98/dotfiles.git

# github-release-binary
ghrb:
  # binary releases
  - name: bottom
    type: binary
    dest: "~/.local/bin"
    destfile: btm
    version_cmd: "btm --version | awk '{print $NF}'"
    # tag: 1.13.0
  - name: exa
    type: binary
    dest: "~/.local/bin"
    destfile: exa
    extra_opts: -j
    include: "bin/exa"
    version_cmd: "exa --version | grep -i ^v | awk '{print $1}'"
  - name: gron
    type: binary
    dest: "~/.local/bin"
    destfile: gron
    version_cmd: "gron --version | awk '{print $NF}'"
  - name: just
    type: binary
    dest: "~/.local/bin"
    destfile: just
    include: "just"
    version_cmd: "just --version | awk '{print $NF}'"
  - name: neovim
    type: archive
    dest: "~/.local/bin"
    destfile: "nvim-linux64/bin/nvim"
    symlink_src: "~/.local/bin/nvim-linux64/bin/nvim"
    symlink_dest: "~/.local/bin/nvim"
    version_cmd: "nvim  --version | grep -i nvim | head -1 | awk '{print $NF}'"
  - name: tokei
    type: binary
    dest: "~/.local/bin"
    destfile: tokei
    version_cmd: "tokei --version | awk '{print $2}'"
  - name: smug
    type: binary
    dest: "~/.local/bin"
    destfile: smug
    version_cmd: "smug --help | grep Version | awk '{print $NF}'"
  - name: tealdeer
    type: binary
    dest: "~/.local/bin"
    destfile: tldr
    version_cmd: "~/.local/bin/tldr --version | awk '{print $2}'"
  - name: topgrade
    type: binary
    dest: "~/.local/bin"
    destfile: topgrade
    version_cmd: "topgrade --version | awk '{print $NF}'"
  - name: yq
    type: binary
    dest: "~/.local/bin"
    destfile: yq
    symlink_src: "~/.local/bin/yq_linux_amd64"
    symlink_dest: "~/.local/bin/yq"
    version_cmd: "yq --version | awk '{print $NF}'"
  - name: fd
    type: binary
    dest: "~/.local/bin"
    destfile: fd
    version_cmd: "~/.local/bin/fd --version | awk '{print $NF}'"
  - name: dust
    type: binary
    dest: "~/.local/bin"
    destfile: dust
    version_cmd: "~/.local/bin/dust --version | awk '{print $NF}'"
  - name: ripgrep
    type: binary
    dest: "~/.local/bin"
    destfile: rg
    version_cmd: "~/.local/bin/rg --version | grep ^ripgrep | awk '{print $2}'"
  - name: vivid
    type: binary
    dest: "~/.local/bin"
    destfile: vivid
    version_cmd: "~/.local/bin/vivid --version | awk '{print $NF}'"
  - name: zoxide
    type: binary
    version_cmd: "~/.local/bin/zoxide --version | awk '{print $NF}'"
    destfile: zoxide
