---

# grog.package
package_list:
  - name: ack
  - name: bat
  - name: curl
  - name: fzf
  - name: git
  - name: htop
  - name: libio-prompter-perl
  - name: libjson-perl
  - name: libjson-xs-perl
  - name: python3-pip
  - name: sudo
  - name: tmux
  - name: vim
  - name: wget

# hussainweb.chezmoi
chezmoi_init_url: git@github.com:hannah98/dotfiles.git

# z.sh url
zsh_url: "https://github.com/rupa/z/raw/master/z.sh"
