---

- name: ensure local bin dir exists
  become: no
  ansible.builtin.file:
    path: "~/.local/bin"
    state: directory
    mode: 0755

- name: Get latest release
  community.general.github_release:
    user: mikefarah
    repo: yq
    action: latest_release
  register: latest

- name: Get binary
  become: no
  unarchive:
    src: "https://github.com/mikefarah/yq/releases/download/{{ latest['tag'] }}/yq_linux_amd64.tar.gz"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin"
    remote_src: true

- name: Create symbolic link
  ansible.builtin.file:
    src: "~/.local/bin/yq_linux_amd64"
    dest: "~/.local/bin/yq"
    state: link

- name: Make gron executable
  become: no
  file:
    path: "~/.local/bin/yq"
    mode: 0755
