# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: /home/bhannah/projects/ansible-encrypted-vault
  rev: d61397468d8c216e2b39c0375c5625a59df96861
  hooks:
  - id: ansible-encrypted-vault
