---
- hosts: all
  connection: local
  #vars_files:
    #- 'vars/vault.yml'

  roles:
    # grog.package should stay at the top
    - role: grog.package
      tags:
        - apt
    - role: hussainweb.chezmoi
      ansible_become_user: root
      tags:
        - chezmoi
        - dotfiles
      become_user: bhannah
    - role: initial-setup
    - role: andrewrothstein.starship
      tags:
        - prompt
        - starship
    - role: vim
      tags:
        - vim
    - role: batcat
      tags:
        - batcat
    - role: tmux
      tags:
        - tmux
    - role: gron
      tags:
        - gron
    - role: vivid
      tags:
        - vivid
    - role: fd
      tags:
        - fd
    - role: dust
      tags:
        - dust
    - role: tokei
      tags:
        - tokei
    - role: z-jump
      tags:
        - z-jump
        - z.sh
    - role: topgrade
      tags:
        - topgrade
      become_user: bhannah
    - role: just
      tags:
        - just
      become_user: bhannah
    - role: bottom
      tags:
        - bottom
      become_user: bhannah

