---
- hosts: all
  connection: local
  vars_files:
    - 'vars/vault.yml'

  roles:
    # grog.package should stay at the top
    - role: grog.package
      tags:
        - apt
    - role: hussainweb.chezmoi
      ansible_become_user: root
      tags:
        - chezmoi
        - dotfiles
      become_user: bhannah
    - role: initial-setup
    - role: andrewrothstein.starship
      tags:
        - prompt
        - starship
    - role: vim
      tags:
        - vim
    - role: batcat
      tags:
        - batcat
    - role: tmux
      tags:
        - tmux
    - role: z-jump
      tags:
        - z-jump
        - z.sh
    - role: github-release-binary
      tags:
        - cli
        - clis
      become_user: bhannah
