---
- hosts: all
  connection: local
  vars_files:
    - 'vars/vault.yml'

  roles:
    # grog.package should stay at the top
    - role: grog.package
      tags:
        - apt
    - role: apt-cacher-ng
      tags:
        - apt
        - apt-cache
    - role: hussainweb.chezmoi
      ansible_become_user: root
      tags:
        - chezmoi
        - dotfiles
      become_user: bhannah
    - role: chezmoi
      tags:
        - chezmoi
        - my-chezmoi
      become_user: bhannah
    - role: initial-setup
    - role: andrewrothstein.starship
      tags:
        - prompt
        - starship
    - role: vim
      tags:
        - vim
    - role: batcat
      tags:
        - batcat
    - role: tmux
      tags:
        - tmux
    - role: github-release-binary
      tags:
        - cli
        - clis
      become_user: bhannah
    - role: gh-release-binary
      tags:
        - cli
        - clis
        - clitest
      become_user: bhannah
    - role: nvm
      tags:
        - nvm
      become_user: bhannah
