---

- name: Check if chezmoi is already installed
  command: chezmoi --version
  register: chezmoi_version_output
  ignore_errors: yes
  changed_when: false

- name: Check dotfiles chezmoi directory
  stat:
    path: ~/.local/share/chezmoi/.git
  register: chezmoi_state

- name: Initialize chezmoi (empty)
  command: "chezmoi init"
  when: not my_chezmoi_init_url

- name: Initialize chezmoi
  command: "chezmoi init --apply --verbose {{ my_chezmoi_init_url }}"
  when: my_chezmoi_init_url
  changed_when: false

