---

- name: ensure local bin dir exists
  become: no
  ansible.builtin.file:
    path: "~/.local/bin"
    state: directory
    mode: 0755

- name: Get latest release of gron repository
  community.general.github_release:
    user: tomnomnom
    repo: gron
    action: latest_release
  register: gron_latest

- name: Get gron binary
  become: no
  unarchive:
    src: "https://github.com/tomnomnom/gron/releases/download/{{ gron_latest['tag'] }}/gron-linux-amd64-{{ gron_latest['tag'] | regex_replace('^v','') }}.tgz"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin"
    remote_src: true

- name: Make gron executable
  become: no
  file:
    path: "~/.local/bin/gron"
    mode: 0755
