---

- name: Get latest release from repository
  community.general.github_release:
    user: bootandy
    repo: dust
    action: latest_release
  register: latest

- name: Install deb
  apt:
    deb: "https://github.com/bootandy/dust/releases/download/{{ latest['tag'] }}/du-dust_{{ latest['tag'] | regex_replace('^v','') }}_amd64.deb"
  become: yes

